spring.application.name=spring-extension-starter-doc
# H2 内存数据库配置
spring.datasource.url=jdbc:mysql://47.119.167.52:3306/test?useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=test
spring.datasource.password=Test@123
# JPA/Hibernate 配置
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
doc.scan-packages=org.source.spring.doc.controller
logging.level.org.source=debug